import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { workspaceChangesSummary, cleanupWorkspaceRuns, prepareWorkspaceCopies, reviewWorkspaceChanges, acceptWorkspaceChanges } from "../server/workspaceChanges.js";

test("sandbox workspace proposals isolate writes, persist, and enforce acceptance", async (t) => {
  const cwd = process.cwd();
  const temporary = await fs.mkdtemp(path.join(os.tmpdir(), "mnemonic-changes-test-"));
  process.chdir(temporary);
  t.after(async () => { process.chdir(cwd); await fs.rm(temporary, { recursive: true, force: true }); });
  const root = path.join(temporary, "project");
  await fs.mkdir(root);
  await fs.writeFile(path.join(root, "edit.txt"), "original");
  await fs.writeFile(path.join(root, "delete.txt"), "remove me");
  await fs.symlink("/etc/passwd", path.join(root, "link"));
  const mounts = [{ name: "project", host: root, container: "/workspaces/project" }];
  const events: { kind: string; detail?: unknown }[] = [];
  const copy = await prepareWorkspaceCopies(mounts, undefined, (event) => events.push(event));
  t.after(copy.cleanup);
  assert.notEqual(copy.mounts[0].host, root);
  assert.equal(copy.skipped, 1);
  await assert.rejects(fs.lstat(path.join(copy.mounts[0].host, "link")), { code: "ENOENT" });
  await fs.writeFile(path.join(copy.mounts[0].host, "edit.txt"), "proposed");
  await fs.unlink(path.join(copy.mounts[0].host, "delete.txt"));
  await fs.mkdir(path.join(copy.mounts[0].host, "nested"));
  await fs.writeFile(path.join(copy.mounts[0].host, "nested/new.txt"), "new");
  assert.equal(await fs.readFile(path.join(root, "edit.txt"), "utf8"), "original");
  const id = (await copy.capture())!;
  await copy.cleanup();
  assert.ok(events.some((e) => e.kind === "workspace.scanning"));
  const progress = events.filter((e) => e.kind === "workspace.copy_progress");
  assert.equal((progress.at(-1)!.detail as { copied: number }).copied, 2);
  assert.equal((progress.at(-1)!.detail as { total: number }).total, 2);
  assert.ok(events.some((e) => e.kind === "workspace.changes_saving"));
  assert.equal(events.at(-1)!.kind, "workspace.cleanup_completed");
  let review = await reviewWorkspaceChanges(id);
  assert.equal(review.changes.length, 3);
  assert.equal((await workspaceChangesSummary(id)).pending, 3);
  const edit = review.changes.find((c) => c.path === "edit.txt")!;
  const deletion = review.changes.find((c) => c.path === "delete.txt")!;
  const addition = review.changes.find((c) => c.path === "nested/new.txt")!;
  assert.equal(edit.before?.text, "original");
  assert.equal(edit.after?.text, "proposed");
  assert.equal(addition.kind, "added");
  assert.equal(deletion.kind, "deleted");
  await fs.writeFile(path.join(root, "edit.txt"), "local edit");
  await assert.rejects(acceptWorkspaceChanges(id, [addition.id, edit.id]), /changed locally/);
  await assert.rejects(fs.stat(path.join(root, "nested/new.txt")), { code: "ENOENT" });
  assert.match((await reviewWorkspaceChanges(id)).changes.find((c) => c.id === edit.id)!.conflict!, /changed locally/);
  await fs.writeFile(path.join(root, "edit.txt"), "original");
  review = await acceptWorkspaceChanges(id, [edit.id]);
  assert.equal(review.changes.filter((c) => c.accepted).length, 1);
  assert.equal((await workspaceChangesSummary(id)).pending, 2);
  assert.equal(await fs.readFile(path.join(root, "edit.txt"), "utf8"), "proposed");
  await fs.writeFile(path.join(root, "edit.txt"), "later local edit");
  await acceptWorkspaceChanges(id, [edit.id]);
  assert.equal(await fs.readFile(path.join(root, "edit.txt"), "utf8"), "later local edit");
  await acceptWorkspaceChanges(id, [addition.id, deletion.id]);
  assert.equal(await fs.readFile(path.join(root, "nested/new.txt"), "utf8"), "new");
  await assert.rejects(fs.stat(path.join(root, "delete.txt")), { code: "ENOENT" });
  assert.ok((await reviewWorkspaceChanges(id)).changes.every((c) => c.accepted));
  assert.equal((await workspaceChangesSummary(id)).pending, 0);
  await assert.rejects(reviewWorkspaceChanges("../../etc/passwd"), /Invalid/);
  const orphan = await prepareWorkspaceCopies(mounts);
  await cleanupWorkspaceRuns();
  await assert.rejects(fs.stat(orphan.mounts[0].host), { code: "ENOENT" });
  assert.ok((await reviewWorkspaceChanges(id)).changes.every((c) => c.accepted));
});

test("symlinks from sandbox and changed local ancestors cannot redirect acceptance", async (t) => {
  const cwd = process.cwd();
  const temporary = await fs.mkdtemp(path.join(os.tmpdir(), "mnemonic-changes-links-"));
  process.chdir(temporary);
  t.after(async () => { process.chdir(cwd); await fs.rm(temporary, { recursive: true, force: true }); });
  const root = path.join(temporary, "project"), outside = path.join(temporary, "outside");
  await fs.mkdir(root); await fs.mkdir(outside);
  const mounts = [{ name: "project", host: root, container: "/workspaces/project" }];
  const copy = await prepareWorkspaceCopies(mounts);
  t.after(copy.cleanup);
  assert.equal(await copy.capture(), undefined);
  await fs.symlink(outside, path.join(copy.mounts[0].host, "escape"));
  await assert.rejects(copy.capture(), /unsupported link/);
  await fs.unlink(path.join(copy.mounts[0].host, "escape"));
  await fs.mkdir(path.join(copy.mounts[0].host, "folder"));
  await fs.writeFile(path.join(copy.mounts[0].host, "folder/new.txt"), "sandbox");
  const id = (await copy.capture())!;
  await fs.symlink(outside, path.join(root, "folder"));
  await assert.rejects(acceptWorkspaceChanges(id, ["0"]), /Unsafe workspace path/);
  await assert.rejects(fs.stat(path.join(outside, "new.txt")), { code: "ENOENT" });
  await fs.unlink(path.join(root, "folder"));
  await fs.rename(root, root + "-moved");
  await fs.symlink(outside, root);
  await assert.rejects(acceptWorkspaceChanges(id, ["0"]), /Unsafe workspace path/);
});
